language: go

go:
  - 1.x

before_install:
  - export GOROOT=$(go env GOROOT)

go_import_path: myitcv.io/immutable

install: true

script:
  - ./_scripts/run_tests.sh
  - ./_scripts/check_git_is_clean.sh
